### ISSUE TITLE
Simple Local Scope for Vue3

### ISSUE THREAD

**Issue by unrevised6419** [posva/vue-local-scope#17]
Created for others who will search a Vue3 alternative

Create a file **LocalScope.vue**

```vue
<template>
	<slot v-bind="$attrs" />
</template>
```

Example how to use it

```vue
<template>
	<LocalScope v-slot="{ classes }" classes="block py-4 text-left">
		<span v-if="loading" :class="classes">Loading</span>
		<span v-else-if="error" :class="classes">Something wrong</span>
		<span v-else-if="results.length === 0" :class="classes">No Results</span>
		<a
			v-for="result in results"
			v-else
			:key="result.url"
			:href="result.url"
			:class="classes"
		>
			{{ result.text }}
		</a>
	</LocalScope>
</template>
```

**Comment by n0099** [comment]
It's won't keep typing due to fallthrough attributes: https://stackoverflow.com/questions/75466435/vue-v-bind-attrs-breaks-typing/77602152#77602152

**Comment by unrevised6419** [comment]
I switched to this implementation which works in the latest Vue3 and is fully typed.

```vue
<template>
	<slot :scope="scope" />
</template>

<script setup lang="ts" generic="T">
defineProps<{ scope: T }>();
</script>
```

**Comment by unrevised6419** [comment]
I created a small library for this https://github.com/allindevelopers/vue-local-scope

Now, it supports types without wrapping them in an object.

**Usage:**

```vue
<template>
	<LocalScope lorem="Lorem Ipsum Dolor Sit Amet" #default="{ lorem }">
		<ol>
			<li>{{ lorem }}</li>
			<li>{{ lorem }}</li>
			<li>{{ lorem }}</li>
		</ol>
	</LocalScope>
</template>
```

**LocalScope**

```vue
<script setup lang="ts" generic="T">
defineOptions({ inheritAttrs: false });
defineProps</* @vue-ignore */ T>();
</script>

<template>
	<slot v-bind="$attrs as T" />
</template>
```

**Comment by eric-gitta-moore** [comment]
@unrevised6419 

Great job! However, I found that the TypeScript hints work in the Vue playground. 

But when I go back to VSCode, this will cause TS to fail. I got `(property) default?: ((props: unknown) => any) | undefined`

[Vue SFC Playground](https://play.vuejs.org/#eNqtUl1v0zAU/SsXCyndtCVCZRIqWUWBSQxNMNEKXiyhkN5mHo5t2TelUpT/znWaZeVje9qb7znnfvq0YuFcum1QzEQeSq8cQUBq3FwaVTvrCa5sWehlaR3CxtsakjS7h2Jq8nrUtuBxA90gjJw00pTWBII6VHAe+UnyAbW28M16vX6WHEmTZ/vW3JQDwtrpgpAjgPyg/Uxbj/W5FC0E8jNIrmIMly40Nby3zMJSESxqpAQ6KWB7GrSlPqFPjWBfletaPbz4rdW8HSQpV4auyzPGnobPs6FVfnA3BvJsXFScCAp8pY2q0ttgDX9GGzOkKG3tlEb/2ZHiK0oxg56JXMFH/PWxx8g3eHKHlzdY/vwPfht2EZPi2mNAv0UpRo4KXyHt6YvlJ9zxeyRru240qx8hv2Cwuokz7mVvG7PmsQ90/bSXvU2UqVbhYkdowt1ScdCo7Hq9FGydd4+sfj/uNH3Z50nT8RX/NObfngZdmIrdQFwMKjToVcnhqjfFGjfK4NBs0oIyN8zTgsiHGWwKHRC6I7b6XnjtrQt5dgxvuNGpqgx/PhxnsJpPouhBR0vKoyfZmj+UWXP350XsAEUAngOyf4zxfYs+nomXmaZn6YtpxCh8HdGz9FU6Fd1vEhJA1Q==)

**Comment by unrevised6419** [comment]
Hey, @eric-gitta-moore, Thanks! Yes, recently were some regressions. I will try to look into it soon, but not sure I could solve it because it may be a problem in the underlying tooling.

https://github.com/vuejs/language-tools/issues/5592
https://github.com/vuejs/rfcs/discussions/505#discussioncomment-11391758
https://github.com/allindevelopers/vue-local-scope/issues/1
