### ISSUE TITLE
Is `false` required for non-transformed props? And if so, why?

### ISSUE THREAD

**Issue by Aaron-Pool** [posva/vue-local-scope#5]
The readme makes it seem like setting `items: false` is required. Is that a correct reading? And, if so, is there reason that non-transformed props don't just default to `false`?

**Comment by posva** [comment]
Setting them is indeed required to make them appear as required props: https://github.com/posva/vue-local-scope/blob/master/src/index.js#L15. I'm sorry I don't get the second question
